sudo: required
services: 
  - docker


before_install:
  - docker build -t shnoby/web-test -f ./web/Dockerfile-dev ./web


script:
  - docker run shnoby/web-test npm test -- --coverage


after_success:
  - docker build -t shnoby/wabacus-web ./web
  - docker build -t shnoby/wabacus-nginx ./nginx
  - docker build -t shnoby/wabacus-worker ./worker
  - docker build -t shnoby/wabacus-api ./api
    #  #login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #  #push to the docker hub
  - docker push shnoby/wabacus-web
  - docker push shnoby/wabacus-nginx
  - docker push shnoby/wabacus-worker
  - docker push shnoby/wabacus-api
    #
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: webcal
  env: multi-container-env
  bucket_name: elasticbeanstalk-us-east-2-776337811758
  bucket_path: multi-container
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY


