version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  api:
    build:
      dockerfile: Dockerfile-dev
      context: ./api
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/store
      - /app/utils
      - /app/static
      - ./api:/app

    environment:
      - DBHOST=postgres
      - DBUSER=postgres
      - DBPASSWORD=postgres_password
      - DBPORT=5432
      - DBNAME=postgres
      - MQHOST=tcp://worker
      - MQPORT=5000
  worker:
    build:
      dockerfile: Dockerfile-dev
      context: ./worker
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - ./worker:/app
    environment:
      - MQWHOST=tcp://*
      - MQWPORT=5000
  web:
    build:
      dockerfile: Dockerfile-dev
      context: ./web
    volumes:
      - /app/node_modules
      - ./web:/app
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile-dev
      context: ./nginx
    ports: 
      - '3000:80'

      

