version: '2'
services: 
  postgres:
    image: 'postgres:latest'
  load-balancer:
    restart: always
    build: 
      context: ./worker/load-balancer
      dockerfile: Dockerfile
    environment:
      - MQPORT_CLIENT=5000
      - MQPORT_WORKER=6000
      - MQHOST=*
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - ./worker:/app
    environment:
      - MQWHOST=tcp://load-balancer
      - MQPORT=6000
      - MQID=worker1
    depends_on:
      - load-balancer
  worker2:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - ./worker:/app
    environment:
      - MQWHOST=tcp://load-balancer
      - MQPORT=6000
      - MQID=worker2
    depends_on:
      - load-balancer
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - load-balancer
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - /app/store
      - ./api:/app
    environment:
      - DBHOST=postgres
      - DBUSER=postgres
      - DBPASSWORD=postgres_password
      - DBPORT=5432
      - DBNAME=postgres
      - MQHOST=tcp://load-balancer
      - MQPORT=5000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
      - worker
    volumes:
      - /app/node_modules
      - ./web:/app
  nginx: 
    restart: always
    build:
      context: ./nginx
    depends_on:
      - web
      - api
    ports: 
      - '8080:80'
  
