version: '2'
services:
  nginx: 
    build:
      dockerfile: Dockerfile
    depends_on:
      - web
  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    network_mode: 'host'
    depends_on:
      - nginx
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - PGDATABASE=postgres
    volumes:
      - ./e2e/cypress:/e2e/cypress
