version: '2'
services: 
  postgres:
    image: 'postgres:latest'
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - ./worker:/app
    environment:
      - MQWHOST=tcp://*
      - MQPORT=5000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - worker
    volumes:
      - /app/node_modules
      - /app/middleware
      - /app/utils
      - /app/static
      - /app/store
      - ./api:/app
    environment:
      - DBHOST=postgres
      - DBUSER=postgres
      - DBPASSWORD=postgres_password
      - DBPORT=5432
      - DBNAME=postgres
      - MQHOST=tcp://worker
      - MQPORT=5000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
      - worker
    volumes:
      - /app/node_modules
      - ./web:/app
  nginx: 
    restart: always
    build:
      context: ./nginx
    depends_on:
      - web
      - api
    ports: 
      - '8080:80'
  
