FROM shnoby/node-zeromq 
WORKDIR '/app'

COPY ./package.json ./

RUN  npm install 

COPY . .

#ENV DBHOST=host.docker.internal
#ENV DBUSER=ruslan
#ENV DBPASSWORD=postgres
#ENV DBPORT=5432
#ENV DBNAME=postgres
#ENV MQHOST=tcp://127.0.0.1
#ENV MQPORT=5000
 


EXPOSE 6937
EXPOSE 5000

CMD ["node","--inspect", "app.js"]
