FROM lgatica/node-zmq:onbuild
WORKDIR '/app'
COPY ./package.json ./
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
    && apk del .gyp
COPY . .
EXPOSE 3000
EXPOSE 5000
CMD ["npm", "run", "start-dev"]
